import { useEffect, useState } from "react";
import { useRoute, Link } from "wouter";
import { useForm, type Path } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useGetPublicChurch, getGetPublicChurchQueryKey, useCreateProfile } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowLeft, ArrowRight, CheckCircle2, HeartHandshake, Loader2 } from "lucide-react";
import { Progress } from "@/components/ui/progress";

const OPTIONS = {
  passions: ["Children", "Youth", "Young adults", "Families", "New Christians", "People who don't know Jesus", "Immigrants/refugees", "Multicultural ministry", "Missions", "People experiencing poverty", "Addiction recovery", "Grief", "Elderly adults", "Prayer", "Discipleship", "Worship", "Community outreach", "Justice/compassion", "Second-generation ministry"],
  interests: ["Children", "Preschool", "Youth", "Young adults", "Worship", "Sound/tech", "Hospitality", "Greeting", "Prayer", "Small groups", "Discipleship", "Outreach", "Missions", "Communications", "Office/admin", "Finance", "Event planning", "Translation", "Transportation", "Maintenance", "Care ministry", "Leadership"],
  gifts: ["Teaching", "Mercy", "Helps", "Administration", "Leadership", "Hospitality", "Giving", "Encouragement", "Faith", "Evangelism", "Discernment", "Wisdom", "Knowledge", "Shepherding", "Service", "Prayer/intercession"],
  naturalStrengths: ["Relational connection", "Encouragement", "Teaching/explaining", "Listening", "Leadership/initiative", "Organizing", "Creative expression", "Problem-solving", "Practical hands-on work", "Hospitality", "Compassion/care", "Communication/storytelling", "Discernment", "Follow-through", "Adaptability"],
  life: ["Grief", "Parenting", "Foster/adoption", "Immigration", "Recovery", "Disability", "Caregiving", "Divorce", "Military service", "Cross-cultural experience", "Mission work", "Financial hardship", "Major career transitions", "Other significant experiences"],
  apest: ["Apostle", "Prophet", "Evangelist", "Shepherd", "Teacher"],
  availability: ["Sunday mornings", "Sunday evenings", "Weekday mornings", "Weekday evenings", "Saturdays", "Flexible/varies"],
} as const;
const choice = z.string();
const assessmentSchema = z.object({
  basicInformation: z.object({ firstName: z.string().min(1, "First name is required"), lastName: z.string().min(1, "Last name is required"), email: z.string().email("Enter a valid email"), phone: z.string(), ageRange: choice.min(1, "Select an age range"), preferredContact: choice.min(1, "Select a contact method"), familySituation: choice.min(1, "Select a family situation"), transportation: choice.min(1, "Select transportation") }),
  churchConnection: z.object({ attendanceLength: choice.min(1, "Select attendance length"), connectionLevel: z.coerce.number().min(1).max(5), followingJesusLength: choice.min(1, "Select an answer"), servedBefore: z.boolean(), previousService: z.string() }),
  passions: z.array(z.string()).min(1, "Select at least one passion"),
  interests: z.array(z.string()).min(1, "Select at least one ministry interest"),
  servingFrequency: choice.min(1, "Select a serving frequency"),
  availability: z.array(z.string()).min(1, "Select at least one time"),
  languageText: z.string(), languageProficiency: z.string(),
  churchDetails: z.object({ membership: z.string(), service: z.string(), previousInvolvement: z.string() }),
  spiritualGifts: z.array(z.string()).min(3, "Choose at least three gifts").max(5, "Choose up to five gifts"), apestPrimary: z.string().min(1, "Select a primary tendency"), apestSecondary: z.string().min(1, "Select a secondary tendency"),
  workingStyle: z.object({ structure:z.string(), focus:z.string(), expression:z.string(), teamwork:z.string(), perspective:z.string(), pace:z.string() }),
  naturalStrengths: z.object({ selected:z.array(z.string()).min(3, "Choose at least three strengths").max(5, "Choose up to five strengths"), notes:z.string() }),
  occupation: z.string(), skills: z.object({ education:z.string(), certifications:z.string(), skills:z.string(), experience:z.string(), uniqueSkills:z.string() }),
  lifeSelected: z.array(z.string()), lifeNotes: z.string(),
  availabilityDetails: z.object({ seasonal:z.string(), specialEvents:z.string(), retreats:z.string(), missionTrips:z.string(), projects:z.string(), commitment:z.string(), responsibility:z.string().min(1, "Share what feels realistic right now") }),
  spiritualHealth: z.object({ prayer:z.string(), scripture:z.string(), worship:z.string(), relationships:z.string(), community:z.string(), rest:z.string(), motivation:z.string(), wellbeing:z.string(), connection:z.string() }),
  preferences: z.object({ setting:z.string(), role:z.string(), routine:z.string(), team:z.string(), work:z.string(), rhythm:z.string() }),
}).superRefine((value, context) => {
  if (value.apestPrimary === value.apestSecondary) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["apestSecondary"], message: "Choose a different secondary tendency" });
  }
});
type Values = z.infer<typeof assessmentSchema>;
 const defaultValues: Values = { basicInformation:{firstName:"",lastName:"",email:"",phone:"",ageRange:"",preferredContact:"email",familySituation:"",transportation:""},churchConnection:{attendanceLength:"",connectionLevel:3,followingJesusLength:"",servedBefore:false,previousService:""},passions:[],interests:[],servingFrequency:"",availability:[],languageText:"",languageProficiency:"",churchDetails:{membership:"",service:"",previousInvolvement:""},spiritualGifts:[],apestPrimary:"",apestSecondary:"",workingStyle:{structure:"",focus:"",expression:"",teamwork:"",perspective:"",pace:""},naturalStrengths:{selected:[],notes:""},occupation:"",skills:{education:"",certifications:"",skills:"",experience:"",uniqueSkills:""},lifeSelected:[],lifeNotes:"",availabilityDetails:{seasonal:"",specialEvents:"",retreats:"",missionTrips:"",projects:"",commitment:"",responsibility:""},spiritualHealth:{prayer:"",scripture:"",worship:"",relationships:"",community:"",rest:"",motivation:"",wellbeing:"",connection:""},preferences:{setting:"",role:"",routine:"",team:"",work:"",rhythm:""} };
type FormProps = { form: ReturnType<typeof useForm<Values>> };
function TextField({ form, name, label, description, multiline = false }: FormProps & {name:Path<Values>;label:string;description?:string;multiline?:boolean}) {
 return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel>{description && <FormDescription>{description}</FormDescription>}<FormControl>{multiline ? <Textarea name={field.name} value={String(field.value ?? "")} onChange={field.onChange} onBlur={field.onBlur} ref={field.ref} rows={3}/> : <Input name={field.name} value={String(field.value ?? "")} onChange={field.onChange} onBlur={field.onBlur} ref={field.ref}/>}</FormControl><FormMessage/></FormItem>}/>;
}
function SelectField({ form, name, label, options, description }: FormProps & {name:Path<Values>;label:string;options:readonly string[];description?:string}) {
 return <FormField control={form.control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel>{description && <FormDescription>{description}</FormDescription>}<Select value={field.value as string} onValueChange={field.onChange}><FormControl><SelectTrigger><SelectValue placeholder="Select an option"/></SelectTrigger></FormControl><SelectContent>{options.map(option=><SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select><FormMessage/></FormItem>}/>;
}
 function MultiSelect({form,name,options,limit}:{form:FormProps["form"];name:"passions"|"interests"|"spiritualGifts"|"lifeSelected"|"availability"|"naturalStrengths.selected";options:readonly string[];limit?:number}) {
 return <FormField control={form.control} name={name} render={({field}) => <FormItem><div className="grid sm:grid-cols-2 gap-2">{options.map(option => { const selected=field.value.includes(option); const disabled=!selected && Boolean(limit && field.value.length >= limit); return <label key={option} className={`flex gap-3 rounded-lg border p-3 text-sm ${disabled?"opacity-50":"cursor-pointer hover:bg-muted/40"}`}><Checkbox checked={selected} disabled={disabled} onCheckedChange={checked=>field.onChange(checked?[...field.value,option]:field.value.filter(value=>value!==option))}/>{option}</label>; })}</div><FormMessage/></FormItem>}/>;
}
function Heading({children,description}:{children:React.ReactNode;description?:string}) { return <div><h3 className="font-serif text-xl font-medium">{children}</h3>{description&&<p className="text-sm text-muted-foreground mt-1">{description}</p>}</div>; }

export default function Assessment() {
 const [, params] = useRoute("/profile/:slug"); const slug=params?.slug ?? "";
 const {data:church,isLoading,error:churchError}=useGetPublicChurch(slug,{query:{enabled:Boolean(slug),queryKey:getGetPublicChurchQueryKey(slug)}});
 const createProfile=useCreateProfile(); const [step,setStep]=useState(0); const [submitError,setSubmitError]=useState("");
 const form=useForm<Values>({resolver:zodResolver(assessmentSchema),defaultValues});
 useEffect(()=>{const subscription=form.watch((values,info)=>{if(info.name) form.clearErrors(info.name as Path<Values>);if(info.name==="apestPrimary"&&values.apestPrimary===values.apestSecondary) form.setValue("apestSecondary","")});return()=>subscription.unsubscribe()},[form]);
 const validateStep=() => {
  const validators: Record<number,{schema:z.ZodType;value:unknown;prefix:string}> = {
   1:{schema:assessmentSchema.shape.basicInformation,value:form.getValues("basicInformation"),prefix:"basicInformation"},
   2:{schema:assessmentSchema.shape.churchConnection,value:form.getValues("churchConnection"),prefix:"churchConnection"},
   3:{schema:z.object({passions:assessmentSchema.shape.passions,interests:assessmentSchema.shape.interests,servingFrequency:assessmentSchema.shape.servingFrequency,availability:assessmentSchema.shape.availability}),value:{passions:form.getValues("passions"),interests:form.getValues("interests"),servingFrequency:form.getValues("servingFrequency"),availability:form.getValues("availability")},prefix:""},
    4:{schema:z.object({spiritualGifts:assessmentSchema.shape.spiritualGifts,apestPrimary:assessmentSchema.shape.apestPrimary,apestSecondary:assessmentSchema.shape.apestSecondary,workingStyle:assessmentSchema.shape.workingStyle,naturalStrengths:assessmentSchema.shape.naturalStrengths}).superRefine((value,context)=>{if(value.apestPrimary===value.apestSecondary)context.addIssue({code:z.ZodIssueCode.custom,path:["apestSecondary"],message:"Choose a different secondary tendency"})}),value:{spiritualGifts:form.getValues("spiritualGifts"),apestPrimary:form.getValues("apestPrimary"),apestSecondary:form.getValues("apestSecondary"),workingStyle:form.getValues("workingStyle"),naturalStrengths:form.getValues("naturalStrengths")},prefix:""},
   5:{schema:z.object({occupation:assessmentSchema.shape.occupation,skills:assessmentSchema.shape.skills,lifeSelected:assessmentSchema.shape.lifeSelected,lifeNotes:assessmentSchema.shape.lifeNotes}),value:{occupation:form.getValues("occupation"),skills:form.getValues("skills"),lifeSelected:form.getValues("lifeSelected"),lifeNotes:form.getValues("lifeNotes")},prefix:""},
   6:{schema:z.object({availabilityDetails:assessmentSchema.shape.availabilityDetails,spiritualHealth:assessmentSchema.shape.spiritualHealth}),value:{availabilityDetails:form.getValues("availabilityDetails"),spiritualHealth:form.getValues("spiritualHealth")},prefix:""},
   7:{schema:z.object({preferences:assessmentSchema.shape.preferences}),value:{preferences:form.getValues("preferences")},prefix:""},
  };
  const current=validators[step]; if(!current)return true; const result=current.schema.safeParse(current.value); if(result.success)return true;
  result.error.issues.forEach(issue=>form.setError([current.prefix,...issue.path].filter(Boolean).join(".") as Path<Values>,{type:"manual",message:issue.message})); return false;
 };
 const next=()=>{if(!validateStep())return;setStep(value=>value+1);window.scrollTo({top:0,behavior:"smooth"})};
 const submit=(data:Values)=>{setSubmitError("");createProfile.mutate({data:{churchSlug:slug,basicInformation:{...data.basicInformation,phone:data.basicInformation.phone||null},churchConnection:{...data.churchConnection,previousService:data.churchConnection.previousService||null},passions:data.passions,interests:data.interests,servingFrequency:data.servingFrequency,availability:data.availability,skills:{occupation:data.occupation||null,uniqueSkills:data.skills.uniqueSkills||null,previousMinistryExperience:data.skills.experience||null,leadershipExperience:null,missionTripExperience:null,lifeExperience:data.lifeNotes||null},languages:data.languageText?{spoken:data.languageText,proficiency:data.languageProficiency||null}:null,churchDetails:data.churchDetails,skillsDetails:data.skills,lifeExperiences:{selected:data.lifeSelected,notes:data.lifeNotes},availabilityDetails:data.availabilityDetails,ministryPreferences:data.preferences,assessmentSections:{spiritualGifts:{topGifts:data.spiritualGifts},apest:{primary:data.apestPrimary||null,secondary:data.apestSecondary||null},personalityStrengths:data.workingStyle,naturalStrengths:{selected:data.naturalStrengths.selected,notes:data.naturalStrengths.notes||null},spiritualHealth:data.spiritualHealth}}},{onSuccess:()=>{setStep(8);window.scrollTo({top:0,behavior:"smooth"})},onError:()=>setSubmitError("We couldn’t submit your profile right now. Please check your connection and try again.")})};
 if(isLoading)return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin text-primary"/></div>;
 if(churchError||!church)return <div className="min-h-screen grid place-items-center p-4"><Card><CardContent className="p-8">Church not found. <Link href="/">Return home</Link></CardContent></Card></div>;
 if(step===0)return <div className="min-h-screen grid place-items-center bg-muted/20 p-4"><Card className="max-w-xl text-center"><CardContent className="p-10 space-y-6"><HeartHandshake className="w-12 h-12 mx-auto text-primary"/><h1 className="font-serif text-4xl">Your Ministry Profile</h1><p className="text-muted-foreground">This is a conversation starter, not a test, diagnosis, or automatic placement tool. Share only what feels comfortable.</p><Button onClick={()=>setStep(1)}>Begin <ArrowRight className="w-4 h-4 ml-2"/></Button></CardContent></Card></div>;
 if(step===8)return <div className="min-h-screen grid place-items-center p-4"><Card className="max-w-md text-center"><CardContent className="p-10 space-y-5"><CheckCircle2 className="w-14 h-14 mx-auto text-primary"/><h1 className="font-serif text-3xl">Thank you</h1><p className="text-muted-foreground">Your profile has been shared with {church.name}. A leader can follow up thoughtfully about next steps.</p><Button asChild><a href={church.profileUrl || "/"}>Return to church profile</a></Button></CardContent></Card></div>;
 return <div className="min-h-screen bg-muted/20"><header className="sticky top-0 z-10 bg-background border-b"><div className="max-w-3xl mx-auto p-4 flex justify-between"><strong>{church.name}</strong><span className="text-sm text-muted-foreground">Step {step} of 7</span></div><Progress value={step/7*100}/></header><main className="max-w-3xl mx-auto p-4 md:p-10"><Form {...form}><form onSubmit={event=>event.preventDefault()}><Card><CardContent className="p-6 md:p-10 space-y-8">
 {step===1&&<><Heading description="Keep this simple and ministry-relevant.">Personal Information</Heading><div className="grid md:grid-cols-2 gap-5"><TextField form={form} name="basicInformation.firstName" label="First name"/><TextField form={form} name="basicInformation.lastName" label="Last name"/><TextField form={form} name="basicInformation.email" label="Email"/><TextField form={form} name="basicInformation.phone" label="Phone (optional)"/><SelectField form={form} name="basicInformation.ageRange" label="Age range" options={["Under 18","18–25","26–35","36–45","46–55","56–65","66+"]}/><SelectField form={form} name="basicInformation.preferredContact" label="Preferred contact method" options={["Email","Phone","Text"]}/><SelectField form={form} name="basicInformation.familySituation" label="Family situation" options={["Single","Married","Parent/caregiver","Empty nester","Other"]}/><SelectField form={form} name="basicInformation.transportation" label="Transportation" options={["Reliable transportation","Sometimes need transportation","Would like to discuss"]}/><TextField form={form} name="languageText" label="Languages spoken (optional)"/><SelectField form={form} name="languageProficiency" label="Language proficiency (optional)" options={["Basic conversation","Conversational","Fluent","Native/bilingual"]}/></div></>}
 {step===2&&<><Heading description="Help pastors understand your relationship with the church.">About Me / Church Connection</Heading><div className="grid md:grid-cols-2 gap-5"><SelectField form={form} name="churchConnection.attendanceLength" label="How long have you attended?" options={["Just visiting","Less than 6 months","6–12 months","1–3 years","3+ years"]}/><SelectField form={form} name="churchConnection.followingJesusLength" label="How long have you followed Jesus?" options={["Still exploring","Less than 1 year","1–3 years","3–5 years","5–10 years","10+ years"]}/><SelectField form={form} name="churchDetails.membership" label="Membership" options={["Member","Not currently a member","Interested in learning more","Prefer not to say"]}/><TextField form={form} name="churchDetails.service" label="Service or congregation you attend (optional)"/><TextField form={form} name="churchDetails.previousInvolvement" label="Previous church involvement (optional)" multiline/></div><FormField control={form.control} name="churchConnection.connectionLevel" render={({field})=><FormItem><FormLabel>How connected do you feel here? (self-reported)</FormLabel><div role="radiogroup" aria-label="Church connection level" className="flex gap-2">{[1,2,3,4,5].map(level=><Button key={level} type="button" role="radio" aria-checked={field.value===level} aria-label={`Connection level ${level} of 5`} variant={field.value===level?"default":"outline"} className="rounded-full w-10 h-10 p-0" onClick={()=>field.onChange(level)}>{level}</Button>)}</div><FormMessage/></FormItem>}/><FormField control={form.control} name="churchConnection.servedBefore" render={({field})=><label className="flex gap-3 rounded-lg border p-4 cursor-pointer"><Checkbox checked={field.value} onCheckedChange={field.onChange}/>Have you served on a team here before?</label>}/><TextField form={form} name="churchConnection.previousService" label="Prior serving experience (optional)" multiline/></>}
 {step===3&&<><Heading>Passions</Heading><p className="text-sm text-muted-foreground">Who or what has God put on your heart?</p><MultiSelect form={form} name="passions" options={OPTIONS.passions}/><Heading>Ministry Interests</Heading><p className="text-sm text-muted-foreground">Actual ministry areas you would like to explore.</p><MultiSelect form={form} name="interests" options={OPTIONS.interests}/><Heading>Availability & Serving Capacity</Heading><SelectField form={form} name="servingFrequency" label="Serving frequency" options={["Weekly","Every other week","Monthly","Occasional/events only"]}/><MultiSelect form={form} name="availability" options={OPTIONS.availability}/></>}
  {step===4&&<><Heading description="Choose three to five gifts that you recognize in yourself. This is a pastoral self-reflection, not a diagnosis, score, or placement tool.">Spiritual Gifts Assessment</Heading><MultiSelect form={form} name="spiritualGifts" options={OPTIONS.gifts} limit={5}/><Heading description="Select distinct primary and secondary tendencies. This is not a diagnosis or score.">APEST Assessment</Heading><div className="grid md:grid-cols-2 gap-5"><SelectField form={form} name="apestPrimary" label="Primary tendency" options={OPTIONS.apest}/><SelectField form={form} name="apestSecondary" label="Secondary tendency" options={OPTIONS.apest.filter(item=>item!==form.watch("apestPrimary"))}/></div><Heading description="Choose the descriptions that feel most useful for a pastoral conversation, not a personality diagnosis.">Personality / Working Style Assessment</Heading><div className="grid md:grid-cols-2 gap-5">{([["structure","Structured","Flexible"],["focus","People-focused","Task-focused"],["expression","Reflective","Expressive"],["teamwork","Independent","Collaborative"],["perspective","Detail-oriented","Big-picture"],["pace","Steady","Fast-paced"]] as const).map(([name,left,right])=><SelectField key={name} form={form} name={`workingStyle.${name}`} label={`${left} or ${right}`} options={[left,right]}/>)}</div><Heading description="Choose three to five strengths you see in yourself in ministry or everyday life. This is self-reflection only; it does not score or place you.">Natural Strength Assessment</Heading><MultiSelect form={form} name="naturalStrengths.selected" options={OPTIONS.naturalStrengths} limit={5}/><TextField form={form} name="naturalStrengths.notes" label="Where do you see these strengths in action? (optional)" description="Share examples from ministry, work, home, or community." multiline/></>}
 {step===5&&<><Heading>Skills & Experience</Heading><div className="space-y-5"><TextField form={form} name="occupation" label="Profession or field of study"/><TextField form={form} name="skills.education" label="Education"/><TextField form={form} name="skills.certifications" label="Certifications"/><TextField form={form} name="skills.skills" label="Technical, creative, language, music, teaching, leadership, financial, trades, healthcare, counseling, technology, cooking, driving, or organization skills" multiline/><TextField form={form} name="skills.experience" label="Relevant experience" multiline/><TextField form={form} name="skills.uniqueSkills" label="What are you good at that the church may not know about?" multiline/></div><Heading description="Optional. Please do not share anything you do not want church leaders to know.">Life Experiences</Heading><MultiSelect form={form} name="lifeSelected" options={OPTIONS.life}/><TextField form={form} name="lifeNotes" label="Optional notes" multiline/></>}
 {step===6&&<><Heading>Availability & Serving Capacity</Heading><div className="grid md:grid-cols-2 gap-5"><SelectField form={form} name="availabilityDetails.seasonal" label="Seasonal availability" options={["Available year-round","School-year only","Summer only","Varies"]}/>{([["specialEvents","Open to special events?"],["retreats","Open to overnight retreats?"],["missionTrips","Open to mission trips?"],["projects","Open to short-term projects?"]] as const).map(([name,label])=><SelectField key={name} form={form} name={`availabilityDetails.${name}`} label={label} options={["Yes","Maybe / discuss","Not right now"]}/>)}</div><SelectField form={form} name="availabilityDetails.commitment" label="Serving rhythm" options={["Ongoing role","Occasional roles","A mix of both"]}/><TextField form={form} name="availabilityDetails.responsibility" label="What serving responsibility feels realistic right now?" multiline/><Heading description="Pastoral self-reflection only — never pass/fail or scored. Share only what you are comfortable sharing.">Spiritual Health</Heading><div className="grid md:grid-cols-2 gap-5">{(["prayer","scripture","worship","relationships","community","rest","motivation","wellbeing","connection"] as const).map(name=><SelectField key={name} form={form} name={`spiritualHealth.${name}`} label={name==="worship"?"Worship/church engagement":name==="community"?"Community/accountability":name==="rest"?"Rest/Sabbath":name==="wellbeing"?"Emotional/spiritual well-being":name==="connection"?"Current connection with God":name[0].toUpperCase()+name.slice(1)} options={["Needs attention","Growing","Steady","Feeling strong","Prefer not to say"]}/>)}</div></>}
 {step===7&&<><Heading>Ministry Preferences & Environment</Heading><p className="text-muted-foreground">Optional preferences help begin a thoughtful conversation, not determine placement.</p><div className="grid md:grid-cols-2 gap-5">{([["setting","Working style","With people","Behind the scenes"],["role","Role preference","Leading","Supporting"],["routine","Environment","Predictable routines","Changing environments"],["team","Team setting","Alone","Small team","Large group"],["work","Ministry expression","Relational","Practical service","Teaching","Administration","Creative work","Outreach"],["rhythm","Role rhythm","Weekly in one role","Occasionally in several roles"]] as const).map(([name,label,...options])=><SelectField key={name} form={form} name={`preferences.${name}`} label={label} options={options}/>)}</div></>}
 {submitError&&<p role="alert" className="rounded-lg bg-destructive/10 text-destructive p-3">{submitError}</p>}
 </CardContent></Card><div className="flex justify-between mt-6"><Button type="button" variant="ghost" onClick={()=>setStep(value=>value-1)}><ArrowLeft className="w-4 h-4 mr-2"/>Back</Button>{step===7?<Button type="button" disabled={createProfile.isPending} onClick={()=>void form.handleSubmit(submit)()}>{createProfile.isPending&&<Loader2 className="w-4 h-4 mr-2 animate-spin"/>}Submit profile</Button>:<Button type="button" onClick={next}>Continue <ArrowRight className="w-4 h-4 ml-2"/></Button>}</div></form></Form></main></div>;
}