import { useRoute, Link } from "wouter";
import { useGetProfile, getGetProfileQueryKey } from "@workspace/api-client-react";
import { ArrowLeft, Mail, Phone, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const empty = "Not shared";
const spiritualGiftMeanings: Record<string, string> = {
  "Administration":"organizing people, resources, and systems effectively", "Apostleship":"pioneering, starting, expanding, and establishing new ministries or works", "Discernment of Spirits":"recognizing what is from God, human influence, or spiritual deception", "Evangelism":"communicating the gospel and helping people respond to Jesus", "Exhortation / Encouragement":"strengthening, motivating, comforting, and challenging others", "Faith":"unusual confidence in God’s power, promises, and provision", "Giving":"generously and joyfully sharing resources to advance God’s work and meet needs", "Healing":"being used by God as an instrument of physical, emotional, or spiritual healing", "Helps / Service":"meeting practical needs and supporting others so ministry can happen", "Hospitality":"welcoming people and creating environments where others feel received and cared for", "Interpretation of Tongues":"interpreting a message spoken in tongues", "Knowledge":"understanding and communicating spiritual truth or insight", "Leadership":"providing direction, motivating others, and helping a group move toward God-given goals", "Mercy":"compassionately caring for people who are hurting, struggling, marginalized, or in need", "Miracles":"being used by God in extraordinary demonstrations of His power", "Pastoring / Shepherding":"caring for, protecting, guiding, and nurturing people spiritually", "Prophecy":"communicating a message believed to be prompted by God for strengthening, correction, encouragement, or direction", "Teaching":"explaining and applying biblical truth so others understand and grow", "Tongues":"speaking in a language or spiritual utterance given through the Holy Spirit", "Wisdom":"applying spiritual truth appropriately to real situations", "Craftsmanship":"using artistic or practical skill for God’s purposes", "Intercession":"persistent, focused prayer for others", "Missionary / Cross-Cultural Ministry":"effectively ministering across cultures and communities", "Music / Worship":"using musical ability to lead and encourage worship", "Celibacy":"a particular grace for remaining unmarried for undivided devotion to ministry", "Voluntary Poverty":"willingly living with less in order to serve God and others",
};
const responseLabels = ["", "Not at all", "A little", "Sometimes", "Often", "Very much"];
function ResponseLabel({ value }: { value: unknown }) {
  return <span className="text-muted-foreground">{typeof value === "number" ? responseLabels[value] || "Response shared" : "Response shared"}</span>;
}
function SpiritualGifts({ value }: { value: unknown }) {
  const record = value && typeof value === "object" ? value as Record<string, unknown> : {};
  const topGifts = Array.isArray(record.topGifts) ? record.topGifts.filter((gift): gift is string => typeof gift === "string") : [];
  const responses = record.responses && typeof record.responses === "object" ? record.responses as Record<string, unknown> : {};
  if (!topGifts.length && !Object.keys(responses).length) return <p className="text-muted-foreground italic">No spiritual gifts reflection shared.</p>;
  return <div className="space-y-5">{topGifts.length > 0 && <div><h3 className="font-medium mb-2">Gifts selected for conversation</h3><div className="space-y-2">{topGifts.map(gift=><div key={gift} className="rounded-lg border border-border/60 p-3"><strong>{gift}</strong><p className="text-sm text-muted-foreground mt-1">{spiritualGiftMeanings[gift] || "Member-selected gift for pastoral conversation."}</p></div>)}</div></div>}{Object.keys(responses).length > 0 && <div><h3 className="font-medium mb-2">Reflection responses</h3><div className="space-y-3">{Object.entries(responses).map(([gift,response])=><div key={gift} className="rounded-lg border border-border/60 p-3"><div className="text-sm font-medium">{gift}</div>{Array.isArray(response) ? <ol className="mt-2 space-y-2 text-sm">{response.map((entry,index)=>{const reflection=entry && typeof entry === "object" ? entry as Record<string, unknown> : {}; return <li key={index}><p>{typeof reflection.prompt === "string" ? reflection.prompt : `Reflection question ${index + 1}`}</p><ResponseLabel value={reflection.response}/></li>;})}</ol> : <div className="text-sm"><ResponseLabel value={response}/></div>}</div>)}</div></div>}</div>;
}
function Value({ label, value }: {label:string;value: unknown}) {
  const text = typeof value === "string" || typeof value === "number" ? String(value) : "";
  return <div className="rounded-lg border border-border/60 bg-card p-3 break-words"><div className="text-xs font-medium text-muted-foreground mb-1">{label}</div><div className={text ? "" : "text-muted-foreground italic"}>{text || empty}</div></div>;
}
function ObjectValues({ value }: {value: unknown}) {
  if (!value || typeof value !== "object") return <p className="text-muted-foreground italic">No details shared.</p>;
  const entries = Object.entries(value as Record<string, unknown>).filter(([,v]) => v !== null && v !== "" && (!Array.isArray(v) || v.length));
  if (!entries.length) return <p className="text-muted-foreground italic">No details shared.</p>;
  return <div className="grid sm:grid-cols-2 gap-3">{entries.map(([key,val]) => <Value key={key} label={key.replace(/([A-Z])/g, " $1").replace(/^./,x=>x.toUpperCase())} value={Array.isArray(val) ? val.join(", ") : typeof val === "object" ? JSON.stringify(val) : val}/>)}</div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}) { return <section className="space-y-3 print:break-inside-avoid"><h2 className="font-serif text-2xl font-medium">{title}</h2><Card className="border-border/60 shadow-sm"><CardContent className="p-5">{children}</CardContent></Card></section>; }
export default function ProfileDetail() {
 const [,params]=useRoute("/profiles/:id"); const id=params?.id?Number(params.id):0; const {data:profile,isLoading,error}=useGetProfile(id,{query:{enabled:!!id,queryKey:getGetProfileQueryKey(id)}});
 if(error)return <div className="container p-8"><p className="text-destructive">Failed to load profile details.</p><Link href="/profiles">Back to profiles</Link></div>;
 if(isLoading||!profile)return <div className="container p-8"><div className="h-48 animate-pulse rounded bg-muted"/></div>;
 const basic=profile.basicInformation; const connection=profile.churchConnection; const skills=profile.skills;
 return <div className="container max-w-5xl mx-auto px-4 py-8 space-y-8 print:max-w-none print:p-0">
  <div className="flex justify-between no-print"><Button variant="ghost" asChild><Link href="/profiles"><ArrowLeft className="w-4 h-4 mr-2"/>Back</Link></Button><Button variant="outline" onClick={()=>window.print()}><Printer className="w-4 h-4 mr-2"/>Print profile</Button></div>
  <header className="rounded-2xl border bg-card p-7 md:p-10"><h1 className="font-serif text-4xl">{profile.memberName}</h1><p className="text-muted-foreground mt-1">Completed {new Date(profile.completedAt).toLocaleDateString()}</p><div className="flex flex-wrap gap-4 mt-5 text-sm"><a className="flex gap-2 hover:text-primary" href={`mailto:${profile.email}`}><Mail className="w-4 h-4"/>{profile.email}</a>{basic.phone&&<a className="flex gap-2 hover:text-primary" href={`tel:${basic.phone}`}><Phone className="w-4 h-4"/>{basic.phone}</a>}</div></header>
  <div className="grid lg:grid-cols-2 gap-8">
   <Section title="Personal information"><div className="grid sm:grid-cols-2 gap-3"><Value label="Age range" value={basic.ageRange}/><Value label="Preferred contact" value={basic.preferredContact}/><Value label="Family situation" value={basic.familySituation}/><Value label="Transportation" value={basic.transportation}/></div><div className="mt-3"><ObjectValues value={basic.languages}/></div></Section>
   <Section title="Church connection"><div className="grid sm:grid-cols-2 gap-3"><Value label="Attending" value={connection.attendanceLength}/><Value label="Following Jesus" value={connection.followingJesusLength}/><Value label="Connection level (self-reported)" value={connection.connectionLevel}/><Value label="Served here before" value={connection.servedBefore ? "Yes" : "No"}/><Value label="Prior service" value={connection.previousService}/></div><div className="mt-3"><ObjectValues value={connection.details}/></div></Section>
   <Section title="Passions"><div className="flex flex-wrap gap-2">{profile.passions.length ? profile.passions.map(x=><Badge key={x}>{x}</Badge>) : <span className="italic text-muted-foreground">No passions shared.</span>}</div></Section>
   <Section title="Ministry interests"><div className="flex flex-wrap gap-2">{profile.interests.length ? profile.interests.map(x=><Badge key={x} variant="outline">{x}</Badge>) : <span className="italic text-muted-foreground">No interests shared.</span>}</div></Section>
   <Section title="Availability & serving capacity"><div className="grid sm:grid-cols-2 gap-3"><Value label="Frequency" value={profile.servingFrequency}/><Value label="Times" value={profile.availability.join(", ")}/></div><div className="mt-3"><ObjectValues value={profile.availabilityDetails}/></div></Section>
     <Section title="Spiritual Gifts Assessment"><p className="text-sm text-muted-foreground mb-3">Member self-reflection, not a diagnosis or placement recommendation.</p><SpiritualGifts value={profile.assessmentSections.spiritualGifts}/></Section>
    <Section title="APEST Assessment"><p className="text-sm text-muted-foreground mb-3">Member self-reflection, not a diagnosis, score, or placement recommendation.</p><ObjectValues value={profile.assessmentSections.apest}/></Section>
    <Section title="Personality / Working Style Assessment"><p className="text-sm text-muted-foreground mb-3">Conversation-oriented self-reflection, not a personality diagnosis.</p><ObjectValues value={profile.assessmentSections.personalityStrengths}/></Section>
    <Section title="Natural Strength Assessment"><p className="text-sm text-muted-foreground mb-3">Member self-reflection; strengths are not ranked, scored, or used for automatic placement.</p><ObjectValues value={profile.assessmentSections.naturalStrengths}/></Section>
   <Section title="Skills & experience"><div className="grid sm:grid-cols-2 gap-3"><Value label="Occupation" value={skills.occupation}/><Value label="Unique skill" value={skills.uniqueSkills}/><Value label="Previous ministry experience" value={skills.previousMinistryExperience}/><Value label="Leadership experience" value={skills.leadershipExperience}/><Value label="Mission trip experience" value={skills.missionTripExperience}/></div><div className="mt-3"><ObjectValues value={skills.details}/></div></Section>
   <Section title="Life experiences"><p className="text-sm text-muted-foreground mb-3">Shared voluntarily; please handle with care and discretion.</p><ObjectValues value={profile.lifeExperiences}/></Section>
   <Section title="Spiritual health"><p className="text-sm text-muted-foreground mb-3">Pastoral self-reflection only, never a pass/fail measure.</p><ObjectValues value={profile.assessmentSections.spiritualHealth}/></Section>
   <Section title="Ministry preferences & environment"><ObjectValues value={profile.ministryPreferences}/></Section>
  </div>
 </div>;
}